# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"na_rm": "00_utils.ipynb",
         "unique_list": "00_utils.ipynb",
         "to_iter": "00_utils.ipynb",
         "sort_asc": "00_utils.ipynb",
         "sort_desc": "00_utils.ipynb",
         "flat_list": "00_utils.ipynb",
         "feature_value_to_df": "00_utils.ipynb",
         "df_append": "00_utils.ipynb",
         "df_from_array": "00_utils.ipynb",
         "numpy_sample": "00_utils.ipynb",
         "ResultDF": "00_utils.ipynb",
         "save_pickle": "00_utils.ipynb",
         "load_pickle": "00_utils.ipynb",
         "list_to_np_array": "00_utils.ipynb",
         "tabular_proc": "01_pre-processing.ipynb",
         "TBPreProc": "01_pre-processing.ipynb",
         "skip_flds": "01_pre-processing.ipynb",
         "remove_outlier": "03_transform.ipynb",
         "filter_outlier": "01_pre-processing.ipynb",
         "boxnwhisker_value": "03_transform.ipynb",
         "subset": "03_transform.ipynb",
         "fill_na": "03_transform.ipynb",
         "fix_missing": "01_pre-processing.ipynb",
         "app_cat": "03_transform.ipynb",
         "dummies": "03_transform.ipynb",
         "scale_vars": "03_transform.ipynb",
         "TBStep": "03_transform.ipynb",
         "noop_step": "03_transform.ipynb",
         "TBTransform": "03_transform.ipynb",
         "drop_features": "03_transform.ipynb",
         "select": "03_transform.ipynb",
         "apply_function": "03_transform.ipynb",
         "noop_transform": "03_transform.ipynb",
         "TBDataset": "04_dataset.ipynb",
         "random_choose": "04_dataset.ipynb",
         "stratify_split": "04_dataset.ipynb",
         "split_time_series": "04_dataset.ipynb",
         "split_by_cats": "04_dataset.ipynb"}

modules = ["utils.py",
           "pre_processing.py",
           "transform.py",
           "dataset.py"]

doc_url = "https://ddpham.github.io/tabint/"

git_url = "https://github.com/ddpham/tabint/tree/master/"

def custom_doc_links(name): return None
